name: my_apk
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: '>=2.19.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  table_calendar: ^3.0.0
  english_words: ^4.0.0
  provider: ^6.0.0
  sqflite: ^2.4.0
  path: ^1.9.0
  intl: ^0.19.0
  path_provider: ^2.1.4
  google_nav_bar: ^5.0.6
  sidebarx: ^0.17.1
  shared_preferences: ^2.3.2
  pdf: ^3.6.0
  printing: ^5.0.0
  mailer: ^6.2.0
  file_picker: ^8.1.4
  collection: ^1.15.0
  number_to_character: ^0.0.12

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/