// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwqgD19ShBBQMWqO-j-5wtJ8KP0OUKkrk',
    appId: '1:608104943174:web:a7ab8590944715ad578447',
    messagingSenderId: '608104943174',
    projectId: 'gest-ia-37315',
    authDomain: 'gest-ia-37315.firebaseapp.com',
    storageBucket: 'gest-ia-37315.firebasestorage.app',
    measurementId: 'G-CKZ2245GLP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXSZG7yHcEUuk4wmUkc8JNA7O2JFH-_Jo',
    appId: '1:608104943174:android:88f7cfc3a594a964578447',
    messagingSenderId: '608104943174',
    projectId: 'gest-ia-37315',
    storageBucket: 'gest-ia-37315.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6FkHuks5Peav4MkvqxfznknjHNOUiAnw',
    appId: '1:608104943174:ios:7f9ed6ecb3446b37578447',
    messagingSenderId: '608104943174',
    projectId: 'gest-ia-37315',
    storageBucket: 'gest-ia-37315.firebasestorage.app',
    iosBundleId: 'com.example.myApk',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC6FkHuks5Peav4MkvqxfznknjHNOUiAnw',
    appId: '1:608104943174:ios:7f9ed6ecb3446b37578447',
    messagingSenderId: '608104943174',
    projectId: 'gest-ia-37315',
    storageBucket: 'gest-ia-37315.firebasestorage.app',
    iosBundleId: 'com.example.myApk',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCwqgD19ShBBQMWqO-j-5wtJ8KP0OUKkrk',
    appId: '1:608104943174:web:0f5b44ba3c03e094578447',
    messagingSenderId: '608104943174',
    projectId: 'gest-ia-37315',
    authDomain: 'gest-ia-37315.firebaseapp.com',
    storageBucket: 'gest-ia-37315.firebasestorage.app',
    measurementId: 'G-51HM1WN9NR',
  );
}
